excludes = ["*.md", "*.gif", ".git/"]
[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
