excludes = ["*.md", "*.gif", ".git/"]

[formatter.alejandra]
command = "alejandra"
excludes = []
includes = ["*.nix"]
options = []

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
